name: sat_m
description: SAT-M de World Vision.
publish_to: 'none'
version: 4.0.0+4

environment:
  sdk: '>=2.21.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.1.12
  flutter_native_splash: ^2.3.2
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.0
  location: ^5.0.0
  lottie: ^2.4.0
  multi_select_flutter: ^4.1.3
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  random_string: ^2.3.1
  signature: ^5.4.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icono_satm_2.jpg"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ff6c00"
  image: "assets/logo/splash_wvi_logo_blanco.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - assets/logo/
    - assets/lottie/
    - assets/icon/
