import 'dart:convert';

FamiliasModelo familiasModeloFromJson(String str) =>
    FamiliasModelo.fromJson(json.decode(str));

String familiasModeloToJson(FamiliasModelo data) => json.encode(data.toJson());

class FamiliasModelo {
  int? id;
  String codaleaSatfamilias;
  //String codaleaPropension;
  String start;
  String end;
  String today;
  int idPais;
  int idDepartamento;
  int idMunicipio;
  int comunidad;
  int patrocinio;
  String nomEncuestado;
  int identidad;
  int edad;
  String nacimiento;
  int sexo;
  int estudia;
  int educacion;
  int estado;
  String telefonoEncuestado;
  int familias;
  int miembros;
  int nina;
  int nino;
  int ambosPadres;
  int nnPatrocinado;
  String idPatrocinio;
  int p01;
  int p02;
  int p03;
  String p04;
  String p05;
  int p06;
  int p07;
  String p08;
  int p09;
  String p10;
  int p11;
  String p12;
  int p13;
  int p14;
  int p15;
  int p16;
  int p17;
  int p18;
  int p18B;
  int p19;
  int p20;
  int p21;
  int p22;
  int p23;
  int p24;
  int p27;
  int p28;
  int p29;
  int p30;
  String p31;
  int p32;
  String otro1;
  int p33;
  int p34;
  String p35;
  int p36;
  int p37;
  int p38;
  int p39;
  int p40;
  int p41;
  int p42;
  int p43;
  int p44;
  int p45;
  int vivienda;
  int p46;
  int p47;
  int p48;
  int p49;
  int p50;
  String p51;
  int ppi1;
  int ppi2;
  int ppi3;
  int ppi4;
  int ppi5;
  int ppi6;
  int ppi7;
  int ppi8;
  int ppi9;
  int ppi10;
  String ppi11;
  String facilitador;
  int telFacilitador;
  String fecha;
  String observaciones;
  String lat;
  String lon;
  String alt;
  String acc;

  FamiliasModelo({
    this.id,
    required this.codaleaSatfamilias,
    //required this.codaleaPropension,
    required this.start,
    required this.end,
    required this.today,
    required this.idPais,
    required this.idDepartamento,
    required this.idMunicipio,
    required this.comunidad,
    required this.patrocinio,
    required this.nomEncuestado,
    required this.identidad,
    required this.edad,
    required this.nacimiento,
    required this.sexo,
    required this.estudia,
    required this.educacion,
    required this.estado,
    required this.telefonoEncuestado,
    required this.familias,
    required this.miembros,
    required this.nina,
    required this.nino,
    required this.ambosPadres,
    required this.nnPatrocinado,
    required this.idPatrocinio,
    required this.p01,
    required this.p02,
    required this.p03,
    required this.p04,
    required this.p05,
    required this.p06,
    required this.p07,
    required this.p08,
    required this.p09,
    required this.p10,
    required this.p11,
    required this.p12,
    required this.p13,
    required this.p14,
    required this.p15,
    required this.p16,
    required this.p17,
    required this.p18,
    required this.p18B,
    required this.p19,
    required this.p20,
    required this.p21,
    required this.p22,
    required this.p23,
    required this.p24,
    required this.p27,
    required this.p28,
    required this.p29,
    required this.p30,
    required this.p31,
    required this.p32,
    required this.otro1,
    required this.p33,
    required this.p34,
    required this.p35,
    required this.p36,
    required this.p37,
    required this.p38,
    required this.p39,
    required this.p40,
    required this.p41,
    required this.p42,
    required this.p43,
    required this.p44,
    required this.p45,
    required this.vivienda,
    required this.p46,
    required this.p47,
    required this.p48,
    required this.p49,
    required this.p50,
    required this.p51,
    required this.ppi1,
    required this.ppi2,
    required this.ppi3,
    required this.ppi4,
    required this.ppi5,
    required this.ppi6,
    required this.ppi7,
    required this.ppi8,
    required this.ppi9,
    required this.ppi10,
    required this.ppi11,
    required this.facilitador,
    required this.telFacilitador,
    required this.fecha,
    required this.observaciones,
    required this.lat,
    required this.lon,
    required this.alt,
    required this.acc,
  });

  factory FamiliasModelo.fromJson(Map<String, dynamic> json) => FamiliasModelo(
        id: json["id"],
        codaleaSatfamilias: json["codalea_satfamilias"],
        //codaleaPropension: json["codalea_propension"],
        start: json["start"],
        end: json["end"],
        today: json["today"],
        idPais: json["idPais"],
        idDepartamento: json["idDepartamento"],
        idMunicipio: json["idMunicipio"],
        comunidad: json["comunidad"],
        patrocinio: json["patrocinio"],
        nomEncuestado: json["nom_encuestado"],
        identidad: json["identidad"],
        edad: json["edad"],
        nacimiento: json["nacimiento"],
        sexo: json["sexo"],
        estudia: json["estudia"],
        educacion: json["educacion"],
        estado: json["estado"],
        telefonoEncuestado: json["telefono_encuestado"],
        familias: json["familias"],
        miembros: json["miembros"],
        nina: json["nina"],
        nino: json["nino"],
        ambosPadres: json["ambos_padres"],
        nnPatrocinado: json["nn_patrocinado"],
        idPatrocinio: json["id_patrocinio"],
        p01: json["p01"],
        p02: json["p02"],
        p03: json["p03"],
        p04: json["p04"],
        p05: json["p05"],
        p06: json["p06"],
        p07: json["p07"],
        p08: json["p08"],
        p09: json["p09"],
        p10: json["p10"],
        p11: json["p11"],
        p12: json["p12"],
        p13: json["p13"],
        p14: json["p14"],
        p15: json["p15"],
        p16: json["p16"],
        p17: json["p17"],
        p18: json["p18"],
        p18B: json["p18b"],
        p19: json["p19"],
        p20: json["p20"],
        p21: json["p21"],
        p22: json["p22"],
        p23: json["p23"],
        p24: json["p24"],
        p27: json["p27"],
        p28: json["p28"],
        p29: json["p29"],
        p30: json["p30"],
        p31: json["p31"],
        p32: json["p32"],
        otro1: json["otro1"],
        p33: json["p33"],
        p34: json["p34"],
        p35: json["p35"],
        p36: json["p36"],
        p37: json["p37"],
        p38: json["p38"],
        p39: json["p39"],
        p40: json["p40"],
        p41: json["p41"],
        p42: json["p42"],
        p43: json["p43"],
        p44: json["p44"],
        p45: json["p45"],
        vivienda: json["vivienda"],
        p46: json["p46"],
        p47: json["p47"],
        p48: json["p48"],
        p49: json["p49"],
        p50: json["p50"],
        p51: json["p51"],
        ppi1: json["ppi1"],
        ppi2: json["ppi2"],
        ppi3: json["ppi3"],
        ppi4: json["ppi4"],
        ppi5: json["ppi5"],
        ppi6: json["ppi6"],
        ppi7: json["ppi7"],
        ppi8: json["ppi8"],
        ppi9: json["ppi9"],
        ppi10: json["ppi10"],
        ppi11: json["ppi11"],
        facilitador: json["facilitador"],
        telFacilitador: json["tel_facilitador"],
        fecha: json["fecha"],
        observaciones: json["observaciones"],
        lat: json["lat"],
        lon: json["lon"],
        alt: json["alt"],
        acc: json["acc"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "codalea_satfamilias": codaleaSatfamilias,
        // "codalea_propension": codaleaPropension,
        "start": start,
        "end": end,
        "today": today,
        "idPais": idPais,
        "idDepartamento": idDepartamento,
        "idMunicipio": idMunicipio,
        "comunidad": comunidad,
        "patrocinio": patrocinio,
        "nom_encuestado": nomEncuestado,
        "identidad": identidad,
        "edad": edad,
        "nacimiento": nacimiento,
        "sexo": sexo,
        "estudia": estudia,
        "educacion": educacion,
        "estado": estado,
        "telefono_encuestado": telefonoEncuestado,
        "familias": familias,
        "miembros": miembros,
        "nina": nina,
        "nino": nino,
        "ambos_padres": ambosPadres,
        "nn_patrocinado": nnPatrocinado,
        "id_patrocinio": idPatrocinio,
        "p01": p01,
        "p02": p02,
        "p03": p03,
        "p04": p04,
        "p05": p05,
        "p06": p06,
        "p07": p07,
        "p08": p08,
        "p09": p09,
        "p10": p10,
        "p11": p11,
        "p12": p12,
        "p13": p13,
        "p14": p14,
        "p15": p15,
        "p16": p16,
        "p17": p17,
        "p18": p18,
        "p18b": p18B,
        "p19": p19,
        "p20": p20,
        "p21": p21,
        "p22": p22,
        "p23": p23,
        "p24": p24,
        "p27": p27,
        "p28": p28,
        "p29": p29,
        "p30": p30,
        "p31": p31,
        "p32": p32,
        "otro1": otro1,
        "p33": p33,
        "p34": p34,
        "p35": p35,
        "p36": p36,
        "p37": p37,
        "p38": p38,
        "p39": p39,
        "p40": p40,
        "p41": p41,
        "p42": p42,
        "p43": p43,
        "p44": p44,
        "p45": p45,
        "vivienda": vivienda,
        "p46": p46,
        "p47": p47,
        "p48": p48,
        "p49": p49,
        "p50": p50,
        "p51": p51,
        "ppi1": ppi1,
        "ppi2": ppi2,
        "ppi3": ppi3,
        "ppi4": ppi4,
        "ppi5": ppi5,
        "ppi6": ppi6,
        "ppi7": ppi7,
        "ppi8": ppi8,
        "ppi9": ppi9,
        "ppi10": ppi10,
        "ppi11": ppi11,
        "facilitador": facilitador,
        "tel_facilitador": telFacilitador,
        "fecha": fecha,
        "observaciones": observaciones,
        "lat": lat,
        "lon": lon,
        "alt": alt,
        "acc": acc,
      };
}
